# Generated by Django 3.0.5 on 2020-08-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_selectedworks_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedworks',
            name='name',
            field=models.CharField(max_length=50, verbose_name='My works'),
        ),
    ]
