# Generated by Django 3.0.5 on 2020-08-25 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200825_0301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selectedworks',
            old_name='name',
            new_name='title',
        ),
    ]
