# Generated by Django 2.2.12 on 2021-03-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_blogharu_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='blogharu',
            name='title',
            field=models.CharField(default=1, max_length=50, verbose_name='my blogs'),
            preserve_default=False,
        ),
    ]
