# Generated by Django 2.2.12 on 2021-03-30 02:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210328_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogharu',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
