# Generated by Django 2.2.12 on 2021-03-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_blogharu_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogharu',
            name='category',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Travel', 'Travel'), ('Education', 'Education'), ('Others', 'Others')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogharu',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogharu',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
