# Generated by Django 2.2.12 on 2021-03-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210330_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogharu',
            name='thumbnail',
            field=models.ImageField(default='blog_thumbnails/blog.jpg', upload_to='blog_thumbnails'),
        ),
        migrations.AlterField(
            model_name='blogharu',
            name='category',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Travel', 'Travel'), ('Techlology', 'Techlology'), ('Motivation', 'Motivation'), ('Others', 'Others')], max_length=15),
        ),
    ]
