# Generated by Django 2.2.12 on 2021-03-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210330_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogharu',
            name='thumbnail',
            field=models.ImageField(upload_to='blog_thumbnails'),
        ),
    ]
