# Generated by Django 2.2.12 on 2021-03-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210330_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogharu',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='blogharu',
            name='image',
            field=models.ImageField(default=1, upload_to='Blog_images'),
            preserve_default=False,
        ),
    ]
